# Generated by Django 5.2.15 on 2026-06-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='score',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='resume_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
